### ISSUE TITLE
php version?

### ISSUE THREAD

**Issue by vlasvlasvlas** [zuzunker/pivottable#1]
Hi!

Is there an alternative to use have this kind of functionality but using php language? thanks!!

amazing userfriendly framework for pivot tables. thanks!

**Comment by zuzunker** [comment]
Hi!
Sorry, but no. I'm strictly a Java programmer, and the program were done by request. It is a bliss, that owner agreed to share it as it is =)

**Comment by vlasvlasvlas** [comment]
:D txs anyway!
